### ISSUE TITLE
Support for query v5

### ISSUE THREAD

**Issue by anerli** [bevm0/trpc-svelte-toolbox#6]
Hi, first of all love the idea of this library and can't wait to add it to my project. It looks like there is a commit recently to update the library so that it works with svelte query v5.xx, but wondering when these changes will be stable / in NPM so that I can use it without downgrading my version of svelte query. Thanks!

**Comment by ap0nia** [comment]
Thanks for supporting the project! If you're interested in trying out the new version, you can try installing the canary version that's published on npm.

`npm install @bevm0/trpc-svelte-query@canary`

**Comment by anerli** [comment]
Thank you!
